//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Quiz_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_test_detail
    {
        public int ID { get; set; }
        public int id_student { get; set; }
        public int test_code { get; set; }
        public int id_question { get; set; }
        public string answer_a { get; set; }
        public string answer_b { get; set; }
        public string answer_c { get; set; }
        public string answer_d { get; set; }
        public string student_answer { get; set; }
        public Nullable<System.DateTime> timestamps { get; set; }
        public Nullable<int> type { get; set; }
    
        public virtual question question { get; set; }
        public virtual student student { get; set; }
        public virtual test test { get; set; }
    }
}
